### ISSUE TITLE
CDN hosting

### ISSUE THREAD

**Issue by jakirkham** [gorhill/lz4-wasm#1]
Would be nice to have access to this via a CDN to make it a little easier to use in webpages.

**Comment by jakirkham** [comment]
Also thanks for your work in getting this into WASM. This is a really great compression algorithm and will be very nice to be able to use this in the web.

**Comment by gorhill** [comment]
Not sure what you have in mind when you say "CDN hosting". You can use <https://rawgit.com/>?

This is rather new work, and not sure I have properly fleshed out the API yet, I plan to use it in another project to find out if I got the API right.
